services:
  - type: web
    name: au-pair-backend
    env: node
    plan: starter
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
